### ISSUE TITLE
Issue 15/7/2020

### ISSUE THREAD

**Issue by eliasecasta** [sipe-daniel/enumerable-methods#2]
Hello guys, nice job! It looks easy for you :P just small recommendations:

- Be careful with your linting, ruby is space sensitive.
- After you are done with the project start converting the simple lines of code to one-liners.
- I am not sure but I think that you are not returning the __method__ if you don't receive a block, check that please.
- Try to test your methods with all the examples that you can find in the enumerable documentation: https://ruby-doc.org/core-2.7.1/Enumerable.html#method-i-one-3F

WAAAAAARRRRRRRRRRRRMMMMMMMMMMMMMM

**Comment by Victorgonbu** [comment]
Thank you very much for  recommendation Elias, we did as told. WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARMMMMM
